# Generated by Django 5.2.6 on 2025-09-18 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_wishlist_unique_together_remove_wishlist_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimpleUser',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
