# Generated by Django 5.2.6 on 2025-09-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_delete_simpleuser_delete_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
